.eslintrc.json, json/project.json, karma.conf.js, readme.md, src/resources/about-food-labels/styles.scss, src/resources/about-food-labels/view.html, src/resources/home/styles.scss, src/resources/home/view.html, src/resources/terms-and-conditions/styles.scss, src/resources/terms-and-conditions/view.html, src/styles/main.scss
* Added formio json
* Added eslint config (Configuration for eslint)
* Added package.json (NPM package configuration)
* Added Karma config (Testing harness framework)
* Added readme.md (Project level readme)
* Added main.scss (Sass stylesheet) - For final output
* Added development of views resources and stylesheets
=> Added initial commit

json/stage-json/foodPantry.json
=> Updated the stage json

src/resources/pdf/legibility.html
Copied and pasted this from Your label page on formio LB
=> C4A-517 changes done by Michael

src/components/help-guide.js, src/config.js, src/environment.js, src/index.js, test/help-guide.test.js
* Did all the code things, tested it
* Removed the other stuff by copying across.
=> C4A-515 - Help guide instructions always closed on mobile

src/components/partials/help-guide-lb-ingredient.js
It took less effort to just press delete once I saw this was a ticket than anything else.
=> Removed the redundant line

src/components/partials/help-guide-lb-storage.js
* Changed the heading.
* Removed the newline for consistency with the other parts of the code.
=> C4A-546 - Changed the storage and use title to General requirements

.eslintrc.json, src/components/button-group.js, src/components/formio-wrapper.js, src/components/help-guide.js, src/config.js, src/environment.js, src/index.js
* Altered the order of the linter add-ons.
* Fixed up where we missed
* Added in the character rule with exeptions.
=> Fix up linter

src/components/button-group.js, src/components/formio-wrapper.js
* Added in check to make sure button isn't re-initialised on every formio load.
* Added in the scroll to top handler that was added into KYFB earlier in the week.
* Removed redundant eslint comment.
=> Fixed the noticable app slowdown

src/components/partials/help-guide-lb-business.js
=> C4A-552 Update to title

src/components/partials/help-guide-lb-business.js, src/components/partials/help-guide-lb-date-mark.js, src/components/partials/help-guide-lb-exclusion.js, src/components/partials/help-guide-lb-ingredient.js, src/components/partials/help-guide-lb-main.js, src/components/partials/help-guide-lb-names.js, src/components/partials/help-guide-lb-statement.js, src/components/partials/help-guide-lb-storage.js, src/resources/about-food-labels/view.html, src/scripts/collapse-expand.js
Collapse and Expand are now getting focus.
=> C4 a 473 collapse all expand all screen reader

src/validations/statements/alcohol.js, src/validations/statements/salt.js, src/validations/storage-and-use/cooking-preparation.js, src/validations/storage-and-use/directions-other-details.js, src/validations/storage-and-use/storage-other-details.js
* Came across some changes in formio not in the codebase so updated the codebase.
* Updated the rules as per the ppt indicating the functionality required.
=> CFA-518 - Hidden text field validations

src/resources/pdf/example-food-label.html, src/resources/your-label/section-one/view.html, src/validations/business-details/address-line-1.js, src/validations/business-details/address-line-2.js, src/validations/business-details/business-name.js, src/validations/business-details/postcode.js, src/validations/business-details/state.js, src/validations/business-details/suburb.js, src/validations/date-marks/best-date.js, src/validations/date-marks/lot-identification.js, src/validations/food-name-and-description/food-description.js, src/validations/food-name-and-description/food-name.js, src/validations/ingredients/ingredients.js, src/validations/statements/alcohol.js, src/validations/statements/edible-oil.js, src/validations/statements/salt.js, src/validations/storage-and-use/cooking-preparation.js, src/validations/storage-and-use/directions-other-details.js, src/validations/storage-and-use/storage-other-details.js
Updated regex using the latest sheet provided by the Cyber Security team
=> C4 a 513 validation changes

src/validations/date-marks/best-date.js, src/validations/statements/salt.js
@nishgakkhar  I think we need a basic validation to make sure no special characters are there
=> C4A-513 date validation

src/components/formio-wrapper.js, src/index.js
* Added a new event triggering for change events to allow for tracking
* Added in the code from the ticket.
* Changed the code to work and be in ES6 format.
=> QOL-7826 - Added tracking code then corrected it to get the right output

src/components/formio-wrapper.js, test/formio-wrapper-events.test.js, test/formio-wrapper.test.js
* Improved the packaging and unpackaging of localstorage data
* Changed the data for the PDF to be the current data not the data that was initialised.
* Cleared the localstorage and form more effectively
=> CFA-560 - Localstorage issues and issues with PDF

src/environment.js
* Changed from DEV urls
* Updated the admin email
=> Add production URLS to environment file

src/components/formio-wrapper.js, src/config.js, src/environment.js, src/resources/your-label/section-four/view.html, src/resources/your-label/section-one/download-label.html, src/resources/your-label/section-one/view.html, src/resources/your-label/section-three/view.html, src/resources/your-label/section-two/view.html
* Email is a new form instance each time.
* PDF download is now behind a config
* Split out PDF code to allow for conditional on formio
* Put config into formio data object to allow for conditional on formio.
=> CFA-577 - Change the way emailing works

src/environment.js
Removed Vani's email address from dev.
=> CFA-577 - Remove Vani from the email

src/components/formio-wrapper.js
=> CFA-577 - Keep previous data for submission

src/components/formio-wrapper.js, src/resources/your-label/section-one/styles.scss
* Added attribute so Formio doesn't keep overwriting it
* Modified CSS to make it work with attribute
* Added in CSS to make non-disabled button look disabled.
=> CFA-530 - Email spinner fix
